apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-sync
  namespace: sops-prod
spec:
  interval: 1m
  targetNamespace: sops-prod
  sourceRef:
    kind: GitRepository
    name: tenant
  path: infra/prod
  prune: true
