apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-sync
  namespace: sops-staging
spec:
  serviceAccountName: tenant2-flux-sa
  interval: 1m
  targetNamespace: sops-staging
  sourceRef:
    kind: GitRepository
    name: tenant
  path: infra/staging
  prune: true
  decryption:
    provider: sops
