apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: sops-staging
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
